### ISSUE TITLE
Associate request freezes the program

### ISSUE THREAD

**Issue by phpwutz** [bh/python-keepass-httpd#11]
When associating, a python application is started on my desktop, but it freezes instantly. killing the python application also kills the server.

tested on MacOS 10.9

**Comment by bh** [comment]
Can you provide a traceback and a "how to reproduce"?

**Comment by amyers735** [comment]
Hi,

I'm not sure if I have the same issue.

I'm using OSX as well (Mavericks).  The version of python is 2.7.5, and python-keepass-httpd was build from the current master (2420833b70fecfeb51464316ec03d387e8bac14f).

Here is the output when I try and associate a database:

```
Please enter the passphrase for database /Users/amyers/Documents/SyncToMobile/passwords/passwords-mac-copy.kdbx: 

[INFO] 2014-04-29 14:42:39 keepass_http.ui.cli: Passphrase accepted
[INFO] 2014-04-29 14:42:39 keepass_http_script: Server started on 127.0.0.1:19455
[INFO] 2014-04-29 14:42:39 werkzeug:  * Running on http://127.0.0.1:19455/
[INFO] 2014-04-29 14:42:46 keepass_http.httpd.server: Got request: test-associate
[INFO] 2014-04-29 14:42:46 keepass_http.httpd.server: Request was successfull: False
[INFO] 2014-04-29 14:42:46 werkzeug: 127.0.0.1 - - [29/Apr/2014 14:42:46] "POST / HTTP/1.1" 200 -
[INFO] 2014-04-29 14:42:47 keepass_http.httpd.server: Got request: test-associate
[INFO] 2014-04-29 14:42:47 keepass_http.httpd.server: Request was successfull: False
[INFO] 2014-04-29 14:42:47 werkzeug: 127.0.0.1 - - [29/Apr/2014 14:42:47] "POST / HTTP/1.1" 200 -
[INFO] 2014-04-29 14:42:47 keepass_http.httpd.server: Got request: associate
Should be the client accepted? [y/N] y
Give the client a name: Chrome
[ERROR] 2014-04-29 14:42:54 keepass_http.httpd.server: Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/httpd/server.py", line 24, in handle
    response = req_map[request_type](request.json)
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/httpd/requests.py", line 70, in __call__
    self.process()
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/httpd/requests.py", line 139, in process
    kpconf.backend.create_config_key(new_client_id, self.request_dict["Key"])
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/backends/libkeepass_backend.py", line 103, in create_config_key
    password=client_key)
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/backends/libkeepass_backend.py", line 75, in add_entry
    entry = etree.SubElement(deepest_group, "Entry")
TypeError: Argument '_parent' has incorrect type (expected lxml.etree._Element, got int)
[INFO] 2014-04-29 14:42:55 werkzeug: 127.0.0.1 - - [29/Apr/2014 14:42:55] "POST / HTTP/1.1" 500 -
```

**Comment by bh** [comment]
I'll look into this. Thanks for reporting.

**Comment by amyers735** [comment]
Thank you.

If it's relevant, I needed to set these options to get it to build:

```
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments
```

Unfortunately I don't have the error message with me at the moment
which led me to find that I needed those argument, but if you wish I
can certain try and reproduce it again.

Regards,
Andrew.

**Comment by bh** [comment]
Hi  @am2605 and @phpwutz,
can you please confirm that 8864bf0235 fixes this issue?

Thank you.

**Comment by phpwutz** [comment]
this issue seems to be resolved with bhs commit :), i'll merge it into the master

**Comment by amyers735** [comment]
Confirmed that it's fixed.  Thank you guys!  Fantastic!
