### ISSUE TITLE
Another issue on OSX - UnicodeEncodeError

### ISSUE THREAD

**Issue by amyers735** [bh/python-keepass-httpd#27]
Here's an error I get when I use a database created in Windows on my Mac.  It seems to occur when I go to a page with certain logins.  I can try and create a test kdbx file if it is useful.

Andrew

```
[ERROR] 2014-05-02 12:46:37 keepass_http.httpd.server: Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/httpd/server.py", line 24, in handle
    response = req_map[request_type](request.json)
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/httpd/requests.py", line 70, in __call__
    self.process()
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/httpd/requests.py", line 160, in process
    json_entry = entry.to_json_dict(self.response_kpc)
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/backends/__init__.py", line 25, in to_json_dict
    return {"Name": kpc.encrypt(self.title),
  File "/Library/Python/2.7/site-packages/keepass_http-0.4.1-py2.7.egg/keepass_http/crypto.py", line 16, in encrypt
    encrypted_message = libkeepass_crypto.aes_cbc_encrypt(message, self.key, self.iv)
  File "build/bdist.macosx-10.9-intel/egg/libkeepass/crypto.py", line 30, in aes_cbc_encrypt
    return cipher.encrypt(data)
  File "build/bdist.macosx-10.9-intel/egg/Crypto/Cipher/blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 8: ordinal not in range(128)
[INFO] 2014-05-02 12:46:37 werkzeug: 127.0.0.1 - - [02/May/2014 12:46:37] "POST / HTTP/1.1" 500 -
```

**Comment by bh** [comment]
Ohhh, It seems that this is not a MacOS related issue.

Probably there is an entry (the title) in the database which contains a non ASCII char.

I'll fix the encoding shit. :S

**Comment by amyers735** [comment]
Awesome - thanks!

**Comment by bh** [comment]
Could you please verify that b23606f fixes this issue?

**Comment by amyers735** [comment]
It certainly does fix it - thank you!
